// OUDE SITUATIE ZONDER MONUMENTEN - gefixed voor 4 punten
const map=L.map("map",{zoomControl:false}).setView([52.516,6.42],15);
window.map=map;

L.control.zoom({position:'bottomleft'}).addTo(map);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19}).addTo(map);

let curMarker=null,accCircle=null;

const bagLayer=L.layerGroup().addTo(map), bagLabel=L.layerGroup().addTo(map);
const rceLayer=L.layerGroup().addTo(map);
const rceSeen=new Set();
const CORR={"MIN04041B02":"MIN04041B03","MIN04041B03":"MIN04041B02"};
function corr(c){return CORR[c]||c;}
const minuutLayer=L.tileLayer.wms("https://services.rce.geovoorziening.nl/misc/wms",{layers:"Minuutplanbegrenzingen",format:"image/png",transparent:true,version:"1.3.0",opacity:0.5});
const radiusSel=document.getElementById('radius'); const status=document.getElementById('status'); const toggleMin=document.getElementById('toggleMin');
if(toggleMin) toggleMin.addEventListener('change',e=>e.target.checked?minuutLayer.addTo(map):map.removeLayer(minuutLayer));
function setStatus(t){if(status)status.textContent=t;}
function box(lat,lng,r){const dLat=r/111320,dLng=r/(111320*Math.cos(lat*Math.PI/180));return{minLa:lat-dLat,maxLa:lat+dLat,minLo:lng-dLng,maxLo:lng+dLng};}
async function getBAGAddresses(p,o){const results=[];if(p&&Array.isArray(p.verblijfsobject)){const hrefs=p.verblijfsobject.map(v=>v&&(v.href||v)).filter(Boolean);for(const href of hrefs){try{const res=await fetch(href);if(!res.ok)continue;const data=await res.json();const v=data&&Array.isArray(data.features)&&data.features.length?(data.features[0].properties||{}):(data.properties||{});if(!v.openbare_ruimte_naam||!v.huisnummer||!v.woonplaats_naam)continue;results.push({straat:v.openbare_ruimte_naam,huisnummer:v.huisnummer,huisletter:v.huisletter||"",toevoeging:v.toevoeging||"",postcode:v.postcode||"",woonplaats:v.woonplaats_naam});}catch(e){console.error("BAG verblijfsobject fout:",href,e);}}}if(results.length)return results;if(!p||!p.identificatie||!o||!o.c)return[];try{const b=box(o.c.lat,o.c.lng,50);const url=`https://api.pdok.nl/kadaster/bag/ogc/v2/collections/verblijfsobject/items?bbox=${b.minLo},${b.minLa},${b.maxLo},${b.maxLa}&limit=100&f=json`;const res=await fetch(url);if(!res.ok)return[];const data=await res.json();const features=Array.isArray(data.features)?data.features:[];for(const f of features){const v=f.properties||{};const rel=v.pand;const hrefs=[];if(Array.isArray(rel))rel.forEach(r=>{if(typeof r==="string")hrefs.push(r);else if(r&&r.href)hrefs.push(r.href);});else if(typeof rel==="string")hrefs.push(rel);else if(rel&&rel.href)hrefs.push(rel.href);const hoortBijPand=hrefs.some(h=>String(h).includes(String(p.identificatie)));if(!hoortBijPand)continue;if(!v.openbare_ruimte_naam||!v.huisnummer||!v.woonplaats_naam)continue;results.push({straat:v.openbare_ruimte_naam,huisnummer:v.huisnummer,huisletter:v.huisletter||"",toevoeging:v.toevoeging||"",postcode:v.postcode||"",woonplaats:v.woonplaats_naam});}}catch(e){console.error("BAG VO zoekfout:",e);}return results;}
async function findRCEByAddress(address){const params=new URLSearchParams();const volledig=[address.straat,address.huisnummer,address.huisletter,address.toevoeging].filter(Boolean).join(' ');params.set('volledigAdres',volledig);if(address.postcode)params.set('postcode',address.postcode);if(address.woonplaats)params.set('woonplaatsnaam',address.woonplaats);const urls=[`https://api.rce.nl/monumenten/zoeken?${params.toString()}`,`https://linkeddata.cultureelerfgoed.nl/graph/rijksmonumenten/query?${params.toString()}`];for(const url of urls){try{const res=await fetch(url);if(!res.ok)continue;const data=await res.json();if(Array.isArray(data))return data;if(Array.isArray(data.resultaten))return data.resultaten;if(Array.isArray(data.results))return data.results;if(Array.isArray(data.features))return data.features.map(f=>f.properties||f);}catch(e){console.error("RCE zoekfout:",e);}}return[];}
function showRCE(monuments,lat,lng){monuments.forEach(m=>{const nr=m.rijksmonumentnummer||m.rijksmonumentNummer||m.monumentnummer||m.identificatie;const key=String(nr||JSON.stringify(m));if(rceSeen.has(key))return;rceSeen.add(key);L.marker([lat,lng],{title:`Rijksmonument ${nr||''}`}).addTo(rceLayer).bindPopup(`<b>Rijksmonument</b><br>${nr||''}`);});}
async function loadRCEForPand(o){const addresses=await getBAGAddresses(o.p,o);let total=0;for(const address of addresses){const monuments=await findRCEByAddress(address);total+=monuments.length;if(monuments.length)showRCE(monuments,o.c.lat,o.c.lng);}if(addresses.length)setStatus(`${addresses.length} BAG-adres(sen) gecontroleerd; ${total} RCE-resultaat/resultaten`);}
async function loadBAG(lat,lng,r){bagLayer.clearLayers();bagLabel.clearLayers();rceLayer.clearLayers();rceSeen.clear();const b=box(lat,lng,r);try{const url=`https://api.pdok.nl/kadaster/bag/ogc/v2/collections/pand/items?bbox=${b.minLo},${b.minLa},${b.maxLo},${b.maxLa}&limit=100&f=json`;const res=await fetch(url);if(!res.ok)throw new Error('BAG HTTP '+res.status);const data=await res.json();const list=Array.isArray(data.features)?data.features:[];for(const f of list){const p=f.properties||{};const c=f.geometry&&f.geometry.coordinates;if(!c)continue;const center=Array.isArray(c)&&c.length>=2&&typeof c[0]==='number'?[c[1],c[0]]:[lat,lng];const o={p,c:{lat:center[0],lng:center[1]},feature:f};const bouw=p.oorspronkelijkbouwjaar||p.oorspronkelijk_bouwjaar||p.bouwjaar||'';L.circleMarker(center,{radius:6}).addTo(bagLayer).bindPopup(`<b>BAG-pand</b><br>Bouwjaar: ${bouw||'onbekend'}`);if(bouw)L.marker(center,{icon:L.divIcon({className:'bag-label',html:String(bouw),iconSize:null})}).addTo(bagLabel);loadRCEForPand(o);}setStatus(`${list.length} BAG binnen ${r}m`);}catch(e){console.error('BAG fout:',e);setStatus('BAG fout');}}
async function loadHistForLocation(lat,lng){try{const url=`https://services.rce.geovoorziening.nl/misc/wfs?service=WFS&version=2.0.0&request=GetFeature&typeNames=misc:Minuutplanbegrenzingen&outputFormat=application/json&srsName=EPSG:4326&bbox=${lng-0.002},${lat-0.002},${lng+0.002},${lat+0.002}`;const res=await fetch(url);if(!res.ok)return;const data=await res.json();(data.features||[]).forEach(f=>{const p=f.properties||{};const code=p.minuutplancode||p.Minuutplancode||p.MINUUTPLANCODE;if(!code)return;const c=corr(code);L.tileLayer(`https://geoservices.hisgis.nl/tiles/minuutplans/{z}/{x}/{y}.png?cut${c}*`,{opacity:0.65,transparent:true,maxZoom:20}).addTo(map);});}catch(e){console.error('Historie fout:',e);}}
let selectedMarker=null;map.on('click',async e=>{const lat=e.latlng.lat,lng=e.latlng.lng,r=Number(radiusSel&&radiusSel.value||100);if(selectedMarker)map.removeLayer(selectedMarker);selectedMarker=L.marker([lat,lng]).addTo(map);setStatus(`Geselecteerd: ${lat.toFixed(5)}, ${lng.toFixed(5)} – BAG laden...`);loadBAG(lat,lng,r);loadHistForLocation(lat,lng);});
